language: cpp

compiler:
 - gcc

os:
 - linux

sudo: required
dist: trusty

before_script: ./utils/travis-ci/prepare.sh

script: ./utils/travis-ci/build.sh

addons:
 apt:
  packages:
  - build-essential
  - cmake
  - cmake-curses-gui
  - libboost-all-dev
  - libxml2-dev
  - ethtool
  - sqlite3
  - libsqlite3-dev
  - libssl-dev
  - libvirt-dev
